### ISSUE TITLE
Support file-based MOTD from the module

### ISSUE THREAD

**Issue by Cervator** [Terasology/ServerMOTD#2]
Either as a standalone file akin to the approach added in MovingBlocks/Terasology#3160 or from a config file like MovingBlocks/Terasology#3227 begins to do using FlexibleConfig (really, one PR back in that case introduced a first config file under `/configs` this PR makes improvements on top)

Both of the options may need to rely on engine work for their optimal implementation.

1. FlexibleConfig is still being implemented and adapted, it isn't super set in stone yet how to use it
1. Reading a file from a module is at present not allowed. I have started thinking about a sandbox file area for modules I hinted at some in https://github.com/MovingBlocks/Terasology/pull/3227#discussion_r165772610

In the meantime it may still be possible to allow the module to look at the _existing_ config system powered by `config.cfg` and if a given item is present then use the value there for the MOTD

More ideas also at https://github.com/MovingBlocks/Terasology/pull/3160#issuecomment-362356733

**Comment by jdrueckert** [comment]
This module was removed from the omega line-up.
If at all, re-integrating it into omega is only planned long-term at which point it needs to be revisited in detail and overhauled.
Until then, this issue only adds noise to the currently relevant module-land issues and will therefore be closed.
