### ISSUE TITLE
Manage the MOTD as an entity

### ISSUE THREAD

**Issue by Cervator** [Terasology/ServerMOTD#3]
Came up as a suggestion on Slack. Chat log follows with some details so we don't lose it :-)

**Flo**
Would it not make sense to simply store it in entities and to simply show a edit window at start instead of the popup if the user has the permission to edit motd?

**Naman-sopho**
Tbh I am still fairly new to Terasology and still learning about all the things that can be accomplished with the current codebase.

Implementing the feature would definitely enhance the module's usability, along with the in-game edit command I am currently working on this would help the host handle MOTD easily

Although not really sure how to implement your suggestion if you could mention some steps or link some docs from the manual would be really helpful. Also ping @cervator for suggestions. (edited)

**cervator**
on MOTD: it is an interesting issue. Where does configuration end and entities take over? In this case on the `postBegin` (or maybe pre-begin?) in  MOTD Authority (only runs on the server) System class you could ask the entity system if an entity exists with a `MotdComponent` attached and if not create one with the given message

then clients could interact by looking up that entity to pull the message for display as well as change it if they have the required permissions

later on (not being implemented yet) that one step for the Authority check could look to see if there is a file or config option set somewhere with a message and if it differs use that one. Clients that update the message should then also provoke an update of the related config/file. I think that could work?

* https://metaterasology.github.io/docs/developing/entitySystem/entitySystem.html +
* https://metaterasology.github.io/docs/developing/networkMultiplayer/networkMultiplayer.html for docs

**Comment by jdrueckert** [comment]
This module was removed from the omega line-up.
If at all, re-integrating it into omega is only planned long-term at which point it needs to be revisited in detail and overhauled.
Until then, this issue only adds noise to the currently relevant module-land issues and will therefore be closed.
