### ISSUE TITLE
Advanced formatting options

### ISSUE THREAD

**Issue by Cervator** [Terasology/ServerMOTD#4]
As suggested over in https://github.com/MovingBlocks/Terasology/issues/2855 it would be an option to support finer formatting in the MOTD using something like Markdown.

While initial implementation should probably focus on the basic message, down the road we could try to support more advanced formats or even embedded images. Exactly what that would entail is still up for definition :-)

We might first need a UI widget that can display more advanced stuff, some of which I think might already exist (some of the help, journaling, or crafting system include embedded images, font work, etc). Then a way to cleanly write the syntax for that in plain text in either a UI editing the MOTD in-game (#3) or a config file of some sort (#2)

The formatting support etc will likely be useful for other things than just the MOTD and parsers naturally already exist, so reuse should be prioritized over writing new stuff from scratch :-)

**Comment by jdrueckert** [comment]
This module was removed from the omega line-up.
If at all, re-integrating it into omega is only planned long-term at which point it needs to be revisited in detail and overhauled.
Until then, this issue only adds noise to the currently relevant module-land issues and will therefore be closed.
